### ISSUE TITLE
Interviewer copied others repo

### ISSUE THREAD

**Issue by saurabhnemade** [sandeepscet/react-The-MovieDB#1]
I see you copied my assignment to the word. 
Original repository can be found at: [https://github.com/saurabhnemade/themoviedb-frontend-challenge](https://github.com/saurabhnemade/themoviedb-frontend-challenge)

**Comment by sandeepscet** [comment]
@saurabhnemade  
Repo was provided by company and asked to fix the issues.  

You can check first commit. Nobody will commit copied repo as single commit 🤣

![Capture](https://user-images.githubusercontent.com/1390862/86087532-1495ba00-bac2-11ea-871e-fbcde9db8c03.PNG)

[themoviedb-frontend-challenge.zip](https://github.com/sandeepscet/react-The-MovieDB/files/4849642/themoviedb-frontend-challenge.zip)

**Comment by saurabhnemade** [comment]
What issues? Its working fine since 2 years. Which company?
Any contact of person who given you this?
I am still in contact with person who actually provide this assignment and that person & I growing more curious about who gave it. Also post screenshots of email.!!

**Comment by saurabhnemade** [comment]
There is literally no line changes other than api key. Which changes did you submit?? 😅😅🤘

**Comment by saurabhnemade** [comment]
And why did they gave you my frontend assignment for backend role.😂😂😂

**Comment by sandeepscet** [comment]
Email screenshot is already there

You can check changes here : https://github.com/sandeepscet/react-The-MovieDB/commits/master

**Comment by saurabhnemade** [comment]
Thanks for the closure mate!! Really appreciate it!! Somewhere some interviewer might have thought "Inko kya hi pata chalega" :sweat_smile:

![Inko-kya-hi-pata-chalega-1024x576](https://user-images.githubusercontent.com/17445338/86109345-e88a3100-bae1-11ea-993f-fa2626d7ce11.jpg)

Now I know why my repositories are becoming more popular. 🤣  I was wondering since few months, why people suddenly start copying my code instead of fork. 🤣 🤣 🤣

**Comment by saurabhnemade** [comment]
BTW good changes. I had thought of making those changes 👍 

I had very little time to complete that assignment so I had just put comments most of the places where improvements could happen. 😄 😄 😄

**Comment by sandeepscet** [comment]
Thanks.

I can see that you posted initial discussion on twitter. but not latest updates. Hope you'll post that also or delete the tweet 😃

**Comment by saurabhnemade** [comment]
BTW this still does not answers "why did they gave you frontend assignment for backend role"?

Plus the screenshot is absolutely edited. Gmail separator starts without any spaces and the one you have posted has a lot of space from left. That is only possible if you copy 2 images and try to merge them with paint or photoshop or any other photo editing tool which btw explains replying to backend role with frontend assignment. It just seems like you merged two different screenshot. I can only think of that since it says backend role and this assignment is purely frontend.

I am not convinced totally whether that email is actually authentic (unless I see gif with scrolling so I can confirm that the poor interviewer actually gave you frontend assignment for backend role). So I am going to keep the tweet. Though I will update it with screenshots and let the community decide itself. 🤟

**Comment by saurabhnemade** [comment]
Yup. will update that on tweet. 👍 The poor interviewer had said backend role and gave you frontend assignment. 🤣
